name 'open-resty'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures open-resty'
long_description 'Installs/Configures open-resty'
version '0.1.0'
